### PR TITLE
Add Support to get launchUrl from AppTemplate

### PR DESCRIPTION
**Pull request by theanandankit**

### CODE REVIEW

**Comment by HerbertYiga** [comment]
cc @ibacher

**Review by ibacher — APPROVED** [review]
@theanandankit Thanks for this. Looks good. My only question is do we need that gsp file?

**Comment by theanandankit** [comment]
@ibacher I think yes, we are using AppDescriptor to get the config parameter and our redirect URL is 

    "url": "smartonfhir/smartAppsRedirect.page?app=smartapps.demoapp"

So. We need this gsp file; without this page, it will throw the `view not found` error.

**Comment by ibacher** [comment]
@theanandankit Perfect! Thanks!

**Pull request merged**
